# Default values for dockercoins-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: prod

replicaCount: 1

image:
  repository: 127.0.0.1:30161
  tag: v0.1

nameOverride: dockercoins

service:
  type: ClusterIP
  port: 80
  names: worker,hasher,rng,webui

ingress:
  services: hasher,rng,webui
  host: 192.168.33.101.nip.io

healthCheck:
  env: prod
  services: hasher,rng,webui
